// Generated by https://quicktype.io

export interface Menus {
  menu: Menu
}

export interface Menu {
  name: string
  items: Item[]
}

export interface Item {
  title: string
  description: string
  url: string
  attributes: Attributes
  children: ItemChild[]
}

export interface Attributes {
  class: null
}

export interface ItemChild {
  title: string
  url: string
  description: null
  children: ChildChild[]
  attributes: Attributes
  id: string
}

export interface ChildChild {
  url: string
  title: string
  description: null
  id: string
}
