query Node {
	route(path: "/es/node/27") {
		... on RouteExternal {
			__typename
		}
		... on RouteInternal {
			__typename
			entity {
				... on NodeRecreationActivity {
					__typename
					id
					title
					button {
						url {
							title
							url
						}
					}
					carruselImages {
						mediaImage {
							url
							alt
						}
					}
					tabsInfo {
						itemsInfo {
							tabTitle
							tabBody {
								processed
							}
							items {
								description
								title
								icon {
									mediaImage1 {
										url
										alt
									}
								}
							}
						}
					}
					textHtml {
						processed
					}
					sectionCifras {
						itemsCifrasTurismo {
							componenteTitle {
								title
								pSubtitle
							}
							icon {
								mediaImage1 {
									url
									alt
								}
							}
						}
					}
					sectionCards {
						componenteTitle {
							title
							pSubtitle
						}
						button {
							url {
								url
								title
							}
						}
						itemsCardPlan {
							componenteTitle {
								title
								pSubtitle
							}
							image {
								mediaImage {
									url
									alt
								}
							}
						}
					}
					metatag {
						... on MetaTagValue {
							__typename
							attributes {
								content
							}
						}
					}
				}
				... on NodeSportSchool {
					__typename
					id
					title
					button {
						url {
							title
							url
						}
					}
					carruselImages {
						mediaImage {
							url
							alt
						}
					}
					tabsInfo {
						itemsInfo {
							tabTitle
							tabBody {
								processed
							}
							items {
								description
								title
								icon {
									mediaImage1 {
										url
										alt
									}
								}
							}
						}
					}
					textHtml {
						processed
					}
					sectionCifras {
						itemsCifrasTurismo {
							componenteTitle {
								title
								pSubtitle
							}
							icon {
								mediaImage1 {
									url
									alt
								}
							}
						}
					}
					sectionCards {
						componenteTitle {
							title
							pSubtitle
						}
						button {
							url {
								url
								title
							}
						}
						itemsCardPlan {
							componenteTitle {
								title
								pSubtitle
							}
							image {
								mediaImage {
									url
									alt
								}
							}
						}
					}
					metatag {
						... on MetaTagValue {
							__typename
							attributes {
								content
							}
						}
					}
				}
				... on NodeRecreationalCenter {
					__typename
					id
					title
					sectionCifras {
						itemsCifrasTurismo {
							componenteTitle {
								title
								pSubtitle
							}
							icon {
								mediaImage1 {
									url
									alt
								}
							}
						}
					}
					button {
						url {
							title
							url
						}
					}
					textHtml {
						processed
					}
					carruselImages {
						mediaImage {
							url
							alt
						}
					}
					tabsInfo {
						itemsInfo {
							tabTitle
							tabBody {
								processed
							}
							items {
								description
								title
								icon {
									mediaImage1 {
										url
										alt
									}
								}
							}
						}
					}
					sectionCifras {
						itemsCifrasTurismo {
							componenteTitle {
								title
								pSubtitle
							}
							icon {
								mediaImage1 {
									url
									alt
								}
							}
						}
					}
					sectionCards {
						componenteTitle {
							title
							pSubtitle
						}
						button {
							url {
								url
								title
							}
						}
						itemsCardPlan {
							componenteTitle {
								title
								pSubtitle
							}
							image {
								mediaImage {
									url
									alt
								}
							}
						}
					}
					metatag {
						... on MetaTagValue {
							__typename
							attributes {
								content
							}
						}
					}
				}
				... on NodeArticle {
					__typename
					id
					title
					path
					body {
						processed
					}
					image {
						url
						title
						alt
					}
					created {
						time
					}
					metatag {
						... on MetaTagValue {
							__typename
							attributes {
								content
							}
						}
					}
				}
				... on NodeHousingProject {
					__typename
					id
					title
					metatag {
						... on MetaTagValue {
							__typename
							attributes {
								content
							}
						}
					}
					livingPlaceSubtitle {
						processed
					}
					livingPlacePrice {
						price
						subsidyApplies
					}
					livingPlaceGallery {
						housingMainSlider {
							items {
								mediaImage {
									url
									alt
								}
							}
						}
						housingMainCard {
							title
							link {
								url
							}
							icon {
								mediaImage1 {
									url
									alt
								}
							}
						}
					}
					tabsInfo {
						itemsInfo {
							tabTitle
							items {
								title
								description
								icon {
									mediaImage1 {
										url
										alt
									}
								}
							}
							tabBody {
								processed
							}
						}
					}
					livingPlaceServices {
						title
						itemsServices {
							icon {
								mediaImage1 {
									url
									alt
								}
							}
							title
						}
					}
					livingPlaceBreaker {
						componentBreaker {
							componenteTitle {
								title
								pSubtitle
							}
							componentButtons {
								buttons {
									url {
										url
										title
									}
								}
							}
							image {
								mediaImage {
									url
									alt
								}
							}
							imageMobile {
								mediaImage {
									url
									alt
								}
							}
						}
					}
					livingPlaceCarrusel {
						componenteTitle {
							title
							pSubtitle
						}
						behaviors {
							background_behavior {
								background_position
								background_style
								select_color
								image {
									alt
									url
								}
							}
							margin_behavior {
								margin_bottom
								margin_left
								margin_right
								margin_top
							}
							padding_behavior {
								padding_bottom
								padding_left
								padding_right
								padding_top
							}
						}
						carruselVivienda {
							... on ProyectosViviendaResult {
								id
								results {
									... on NodeHousingProject {
										id
										title
										livingPlaceSubtitle {
											processed
										}
										livingPlaceLogo {
											mediaImage {
												url
												alt
											}
										}
										livingPlacePrice {
											price
											subsidyApplies
										}
										path
										tabsInfo {
											itemsInfo {
												items {
													title
													description
													icon {
														mediaImage1 {
															url
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
				... on NodeLodging {
					__typename
					title
					subTitle
					carruselImages {
						mediaImage {
							alt
							url
						}
					}
					lodgingCard {
						price
						image {
							mediaImage {
								url
								alt
							}
						}
						button {
							url {
								url
								internal
							}
						}
					}
					lodgingDescription {
						processed
					}
					lodgingServices {
						textHtml {
							processed
						}
						itemsIcons {
							icon {
								mediaImage1 {
									url
									alt
								}
							}
							title
						}
						title
					}
					lodgingSchedules {
						componenteTitle {
							title
							pSubtitle
						}
						checkOut
						checkIn
						textHtml {
							processed
						}
					}
					lodgingRates {
						season {
							title
							itemSeason {
								entry
								categoriaA
								categoriaB
								categoriaC
								categoriaD
							}
							description {
								processed
							}
						}
						title
					}
					lodgingPayAttention {
						processed
					}
					lodgingInfoLegal {
						processed
					}
					sectionCifras {
						itemsCifrasTurismo {
							icon {
								mediaImage1 {
									url
									alt
								}
							}
							componenteTitle {
								title
								pSubtitle
							}
						}
					}
					lodgingMapCard {
						link {
							url
						}
						title
					}
					sectionCards {
						itemsCardPlan {
							image {
								mediaImage {
									url
									alt
								}
							}
							componenteTitle {
								title
								pSubtitle
							}
						}
						componenteTitle {
							title
							pSubtitle
						}
						button {
							url {
								url
								title
							}
						}
					}
					lodgingInfo {
						textHtml {
							processed
						}
						button {
							url {
								url
								title
							}
						}
					}
				}
			}
		}
	}
}