... on NodeLanding {
	__typename
	id
	title
	metatag {
		... on MetaTagValue {
			__typename
			attributes {
				content
			}
		}
	}
	content {
		... on ParagraphContainerTabsCardsIcon {
			id
			componentTabsCard {
				tabsTitle
				tabs {
					tabTitle
					itemsCard {
						title
						link {
							url
						}
						icon {
							mediaImage1 {
								url
								alt
							}
						}
					}
				}
			}
		}
		... on ParagraphContainerCarruselLivingPlace {
			id
			componentCarruselVivienda {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				carruselVivienda {
					... on ProyectosViviendaResult {
						id
						results {
							... on NodeHousingProject {
								id
								title
								livingPlaceSubtitle {
									processed
								}
								livingPlaceLogo {
									mediaImage {
										url
										alt
									}
								}
								livingPlacePrice {
									price
									subsidyApplies
								}
								path
								tabsInfo {
									itemsInfo {
										items {
											title
											description
											icon {
												mediaImage1 {
													url
													alt
												}
											}
										}
									}
								}
							}
						}
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
			}
		}
		... on ParagraphContainerComponentConvenio {
			id
			componentCarruselConveni {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				button {
					url {
						url
						title
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
				itemsCardImage {
					title
					image {
						mediaImage {
							url
							alt
						}
					}
					link {
						url
					}
				}
			}
		}
		... on ParagraphContainerBreaker {
			id
			componentBreaker {
				sectionSubtitle
				sectionTitle
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				componentButtons {
					buttons {
						url {
							url
							title
						}
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
				image {
					mediaImage {
						url
						alt
					}
				}
				imageMobile {
					mediaImage {
						alt
						url
					}
				}
			}
		}
		... on ParagraphContainerNewstest {
			id
			componentNewstest {
				viewNews {
					... on NoticesGraphql1Result {
						id
						results {
							... on NodeNews {
								title
								path
								created {
									timestamp
								}
								newsImage {
									mediaImage {
										url
										alt
									}
								}
							}
						}
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
				button {
					url {
						title
						url
					}
				}
			}
		}
		... on ParagraphContainerCifra {
			id
			componentCifras {
				itemsCifras {
					title
					eyebrow
					icon {
						mediaImage1 {
							url
							alt
						}
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
			}
		}
		... on ParagraphContainerSlideBanner {
			id
			componentSlideBanner {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				itemsBanner {
					componenteTitle {
						title
						pSubtitle
					}
					image {
						mediaImage {
							url
							alt
						}
					}
					button {
						url {
							url
							title
						}
					}
				}
			}
		}
		... on ParagraphContainerSectionHelpCenter {
			id
			componentHelpCenter {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
				itemsCardsHelp {
					title
					link {
						url
					}
				}
			}
		}
		... on ParagraphTextoHtmlYBotonOpcional {
			id
			componentTextHtmlButton {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				button {
					url {
						url
						title
					}
				}
				textHtml {
					processed
				}
				imageTextHtml {
					mediaImage2 {
						alt
						url
					}
				}
			}
		}
		... on ParagraphContainerBreakerCardsIcon {
			id
			componentBreakerCards {
				itemsCard {
					title
					icon {
						mediaImage1 {
							url
							alt
						}
					}
				}
				title
				textHtml {
					processed
				}
			}
		}
		... on ParagraphContainerCardsIcon {
			id
			componentCardsIcon {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				itemsCard {
					title
					link {
						title
						url
					}
					icon {
						mediaImage1 {
							title
							url
						}
					}
				}
				sectionTitle
			}
		}
		... on ParagraphContainerSectionLink {
			id
			componentSectionLinks {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				itemsCardsLink {
					componenteTitle {
						pSubtitle
						title
					}
					button {
						url {
							title
							url
						}
					}
				}
			}
		}
		... on ParagraphContainerCarruselRecreational {
			id
			componentCarruselRecreation {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				componenteTitle {
					pSubtitle
					title
				}
				viewRecreationalCenter {
					... on CarruselRecreationCentersResult {
						id
						results {
							... on NodeRecreationalCenter {
								id
								title
								path
								carruselImages {
									mediaImage {
										alt
										url
									}
								}
							}
						}
					}
				}
			}
		}
		... on ParagraphContainerTabsVideo {
			id
			componentTabsVideo {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				componenteTitle {
					pSubtitle
					uuid
				}
				itemsTabVideo {
					titleTab
					videos {
						path
						remoteVideo
					}
				}
			}
		}
		... on ParagraphSlideAgreementsFeature {
			id
			componentSlideAgreements {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				button {
					url {
						url
						title
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
				itemsCardsAgreementsFeatures {
					componenteTitle {
						pSubtitle
						title
					}
					image {
						mediaImage {
							url
							alt
						}
						path
					}
					discountRate
				}
			}
		}
		... on ParagraphContainerTextHtml {
			id
			componentTextHtml {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				textHtml {
					processed
				}
			}
		}
		... on ParagraphContainerIconsGrid {
			id
			componentIconsGrid {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				itemsIcons {
					icon {
						mediaImage1 {
							url
							alt
						}
					}
					title
				}
				textHtml {
					processed
				}
			}
		}
		... on ParagraphSlideTurismo {
			componentSlideTurism {
				behaviors {
					background_behavior {
						background_position
						background_style
						select_color
						image {
							url
							alt
						}
					}
					margin_behavior {
						margin_bottom
						margin_left
						margin_right
						margin_top
					}
					padding_behavior {
						padding_bottom
						padding_left
						padding_right
						padding_top
					}
				}
				persons: slideTurismo(
				filter: { key: "field_to_whom_target_id", value: "Personas" }
				) {
					... on TurismoSlideResult {
						results {
							... on NodeRecreationActivity {
								title
								path
								carruselImages {
									mediaImage {
										url
										alt
									}
								}
							}
						}
					}
				}
				enterprises: slideTurismo(
				filter: { key: "field_to_whom_target_id", value: "Empresas" }
				) {
					... on TurismoSlideResult {
						results {
							... on NodeRecreationActivity {
								title
								path
								carruselImages {
									mediaImage {
										url
										alt
									}
								}
							}
						}
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
			}
		}
		... on ParagraphContainerSlideLodging {
			id
			componentSlideLodging {
				behaviors {
					background_behavior {
						background_position
					}
				}
				componenteTitle {
					title
					pSubtitle
				}
				slideLodging {
					... on ViewLodgingResult {
						id
						results {
							... on NodeLodging {
								id
								title
								subTitle
								lodgingServices {
									itemsIcons {
										title
										icon {
											mediaImage1 {
												url
												alt
											}
										}
									}
								}
								petFriendly
								seasonalDiscount
								path
								carruselImages {
									mediaImage {
										url
										alt
									}
								}
							}
						}
					}
				}
			}
		}
	}
}